# Generated by Django 5.0.6 on 2024-07-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_date_of_birth_userprofile_date_of_birt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_of_birt',
            new_name='date_of_birth',
        ),
    ]
